<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$name = $email = '';
if($customerSession->isLoggedIn()) {
    $name = $customerSession->getCustomer()->getName();  // get  Full Name
    $email = $customerSession->getCustomer()->getEmail();
}
?>
<div class="charity-form">
	<div class="page-title">
		<h3><?= __('Please Enter your suggested Cause') ?></h3>
	</div>
    <br/>
	<div class="form-section">
		<form onSubmit="return checkCaptcha();" class="form charity" action="<?= $this->getUrl('charitysuggestion/index/post') ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
			<?php echo $block->getBlockHtml('formkey')?>
			<fieldset class="fieldset">
				<legend class="legend"><span><?= __('About you') ?></span></legend><br>
				<div class="field">
		            <label class="label" for="name"><span><?= __('Your Name') ?></span></label>
		            <div class="control">
		                <input type="text" id="name" name="name" title="Your Name" value="<?= $name; ?>" class="input-text required-entry" data-validate="{required:false}" autocomplete="off">
		            </div>
		        </div> 
		  
		        <div class="field">
		            <label class="label" for="email"><span><?= __('Email Address') ?></span></label>
		            <div class="control">
		                <input type="text" id="email" name="email" title="Email Address" value="<?= $email; ?>" class="input-text required-entry" data-validate="{required:false}" autocomplete="off">
		            </div>
		        </div>
		   

		        <legend class="legend"><span><?= __('Your Suggested Cause') ?></span></legend><br>
		        <div class="field required">
		            <label class="label" for="org_name"><span><?= __('Cause Name') ?></span></label>
		            <div class="control">
		                <input type="text" id="org_name" required name="org_name" title="Organisation Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off">
		            </div>
		        </div>
		        <div class="field required">
		            <label class="label" for="website_url"><span><?= __('Website URL') ?></span></label>
		            <div class="control">
		                <input type="text" id="website_url" required name="website_url" title="Website URL" class="input-text required-entry" data-validate="{required:true}" autocomplete="off">
		            </div>
		        </div>
		        <div class="field required">
		            <label class="label" for="charitytype"><span><?= __('Please select the category that applies to your Cause') ?><?= __('(CTRL CLICK TO SELECT MULTIPLE)') ?></span></label>
		            <div class="control">
		                <select  class="required-entry" id="charitytype" name="charitytype[]" multiple="multiple" size="10" required>
		                	<option value="" disabled="">Please Select</option>
		                	<option value="Arts, Culture & Humanities"><?= __('Arts, Culture & Humanities') ?></option>
		                	<option value="Civil Rights, Social Action & Advocacy"><?= __('Civil Rights, Social Action & Advocacy') ?></option>
		                	<option value="Crime & Legal-Related"><?= __('Crime & Legal-Related') ?></option>
		                	<option value="Diseases, Disorders & Medical Disciplines"><?= __('Diseases, Disorders & Medical Disciplines') ?></option>
		                	<option value="Education"><?= __('Education') ?></option>
		                	<option value="Employment"><?= __('Employment') ?></option>
		                	<option value="Environment"><?= __('Environment') ?></option>
		                	<option value="Food, Agriculture & Nutrition"><?= __('Food, Agriculture & Nutrition') ?></option>
		                	<option value="Health Care"><?= __('Health Care') ?></option>
		                	<option value="Housing & Shelter"><?= __('Housing & Shelter') ?></option>
		                	<option value="Human Services"><?= __('Human Services') ?></option>
		                	<option value="International, Foreign Affairs & National Security"><?= __('International, Foreign Affairs & National Security') ?></option>
		                	<option value="Medical Research"><?= __('Medical Research') ?></option>
		                	<option value="Mental Health & Crisis Intervention"><?= __('Mental Health & Crisis Intervention') ?></option>
		                	<option value="Philanthropy, Voluntarism & Grantmaking Foundations"><?= __('Philanthropy, Voluntarism & Grantmaking Foundations') ?></option>
		                	<option value="Public & Social Benefit"><?= __('Public & Social Benefit') ?></option>
		                	<option value="Public Safety, Disaster Preparedness & Relief"><?= __('Public Safety, Disaster Preparedness & Relief') ?></option>
		                	<option value="Recreation & Sports"><?= __('Recreation & Sports') ?></option>
		                	<option value="Religion Related"><?= __('Religion Related') ?></option>
		                	<option value="Science & Technology"><?= __('Science & Technology') ?></option>
						</select>
		            </div>
		        </div>
		        <div class="field required">
		            <label class="label" for="howhear"><span><?= __('How did you hear about points4purpose?') ?></span></label>
		            <div class="control">
		                <select class="required-entry" id="howhear" name="howhear" required>
		                	<option value="" disabled="" selected="">Please Select</option>
		                	<option value="Word of mouth">Word of mouth</option>
		                	<option value="Google Search">Google Search</option>
		                	<option value="Social media">Social media</option>
		                	<option value="Conference or event">Conference or event</option>
		                	<option value="Saw another charity or corporate using P4P">Saw another charity or corporate using P4P</option>
		                	<option value="I have my own P4P account">I have my own P4P account</option>
		                	<option value="Email from P4P">Email from P4P</option>
		                	<option value="Other">Other</option>
						</select>
		            </div>
		        </div>
			</fieldset>
           <!-- div to show reCAPTCHA -->
            <div class="form-group required">   
				<div class="g-recaptcha required" id="recaptcha"
					 data-sitekey="6Lcgw0kjAAAAANXGOKskvZrjZ30eEGvjnLznZ5IK">
				</div>
				 <div style="display:none" id="error-msg">
					  <span><?php echo __('This is a required field.') ?></span>
				 </div>
            </div>
			
			<div class="actions-toolbar">
		        <div class="primary">
		            <button type="submit" class="action submit primary" title="<?= __('Submit') ?>">
		                <span><?= __('Submit') ?></span>
		            </button>
		        </div>
		    </div>

		    <div class="field">
		    	<h4><?= __('Thanks for your suggestion') ?></h4>
		    
		    </div>
		</form>
	</div>
</div>


<script src="https://www.google.com/recaptcha/api.js" type="text/javascript" xml="space"></script>
<script>
    function checkCaptcha() {
        if ((jQuery('#g-recaptcha-response').val()) === '') {
            jQuery('#error-msg').css('display', 'block');
            jQuery('#error-msg').css('color', '#df280a');
            jQuery('#error-msg').css('font-size', 13);
            return false;
        }else {
            jQuery('#error-msg').css('display', 'none');
        }
    }
</script>