
<?php
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
    $storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
    $storeID       = $storeManager->getStore()->getStoreId(); 
    $storeName     = $storeManager->getStore()->getName();
    $customerData = $customerSession->getCustomer();
    
  //  echo $customerSession->getData('selected_charity');

   //   echo  $storeName.$customerData->getData('selected_charity')."fdsfdsfsdfsdfds";
//            echo '<style>.otherchars{dispaly:none!important;}</style>';
              if ($customerData->getData('selected_charity') == "No Kid Hungry"){
         //   echo  $customerData->getData('selected_charity');
            echo '<style>.othercharsa{dispaly:none!important;}</style>';
      }

    if($customerSession->isLoggedIn()) {
      if ( $customerData->getData('selected_charity') == "No Kid Hungry"){
          echo  $customerData->getData('selected_charity');
            echo '<style>.otherchars{dispaly:none!important;}<\style>';
      }
 
          
    }
?>

<?php
$host = $_SERVER['SERVER_NAME'];
?>

<style>
 
.nav.item {
    list-style-type: none;
}

</style>
