<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<link rel="stylesheet" type="text/css" href="/assets/catpages.css?gfdgfdg"></link>
<style type="text/css">
  @media (max-width: 500px)
  {
    .action.primary, .action-primary, .amshopby-button, .am-filter-go {

    font-size: 8px!important;
}
  }

  /* JOJ */

  .page-header, .item.product.product-item{box-shadow: 0 3px 10px rgb(0 0 0 / 0.2); !important; border-radius: 5px; margin-bottom: 10px!important;}
  .products-grid .product-item-info{transition:all 0.5s ease;}
  .products-grid .product-item-info:hover, .products-grid .product-item-info.active{
    border:none !important; box-shadow: 0 3px 10px rgb(0 0 0 / 0.2); border-radius: 5px;
  }
  .earning-product-list {
    font-size: 0.9em;
    clear: both;
    margin-bottom: 0.9em;
}
.framelogin,.framelogin a, .framelogin span{    color: red!important;

    
    width: 100%;
}
.breadcrumbs .pages{
  float: right;
      font-size: 10px!important;
}
.breadcrumbs .pages .items .item:after{
  content: unset!important;
  font-family: unset!important;
}

.breadcrumbs .pages .action.next:before,.breadcrumbs .pages .action .next, .breadcrumbs .pages .items .item {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 10px;
    line-height: 12px!important;
  }

.breadcrumbs .page{
  line-height: 18px!important;
}
.breadcrumbs .items{
  max-width: 400px;
    display: inline-block;
}
.breadcrumbs .item:not(:last-child):after {
    
    line-height: unset!important;
    
}
.breadcrumbs .items .item:after{
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 10px;
    line-height: 18px;
   # content: unset!important;
  #  font-family: unset!important;
    margin: unset!important;
    vertical-align: unset!important;
    display: unset!important;
    font-weight: unset!important;
    overflow: unset!important;
    speak:unset!important;
    text-align: center;
}
.product-image-photo {
  
    margin: unset!important;

}
.product-image-container img {
    max-width: 100%!important;
}
.item.product.product-item {
    padding: unset!important;
}
.cant-find{
  text-align:center!important;

    padding-top: 8px;
}
</style>

<?php
$_productCollection = $block->getLoadedProductCollection();
$count_productCollection = $block->getLoadedProductCollection()->count();
//$productCount = $collection->count();
/** @var \Magento\Catalog\Helper\Output $_helper */
//print_r($block->getLoadedProductCollection());
$_helper = $block->getData('outputHelper');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$context = $objectManager->get('Magento\Framework\App\Http\Context');
$isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
//$whereweare = $block->getRequest()->getParam('id');
$whereweare = $block->getUrl();
 //$query = ['str1' => 'value1', 'str2' => 'value2',];
    $whereweare = $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);

    if (strpos($whereweare, "select-charity") || strpos($whereweare, "682")){
        $whereweare = 'yes';
         $selcharpage = 1;
         //<style>dli.[data-label]:first-of-type {display:none;} <style>
         echo '<h2 class="title-page ">Select the cause of your choice</h2>
         <div class="container searchbit"><div class="searchinner"><form id="pg-categorysearch-form" class="category-search-form" action="/catalogsearch/result/" method="get" _lpchecked="1"><div class="outerinput">
<input type="text" class="input--full" autocomplete="off" value="" name="q" placeholder="Search for causes" maxlength="128"></div>
<input type="hidden" name=cat value=682><button class="btn btn--wd wave waves-effect waves-effect waves-effect sbut" type="submit">Search</button></form></div></div>
<div class="cant-find"><p>Can\'t find you Charity? <a id="categorySearchBtn" href="/charitysuggestion">Click here</a></p></div>
<style>.title-page{  text-align: center;
    color: #0096a5!important;}.page-title-wrapper{display:none;}.items.am-filter-items-attr_category_ids.am-labels-folding li:nth-child(2){display: none!important;}.searchbit{text-align: center;}.outerinput{max-width: 400px;
    display: inline-block;}.sbut{height: 30px!important;
    margin-bottom: 4px!important;}</style>';
    }else{
         $whereweare = 'no';
         $selcharpage = 0;

                    
////////////////////////////////////////
//// COUNt IT USING JS on Frontend ////
////////////////////////////////////// 

        // echo 'noncharstuff';
         //echo $count_productCollection.'Items';
         echo '<div class="container searchbit"><div class="searchinner"><form id="pg-categorysearch-form" class="category-search-form" action="/catalogsearch/result/" method="get" _lpchecked="1">
<div class="outerinput"><input type="text" class="input--full" autocomplete="off" value="" name="q" placeholder="Search for a store" maxlength="128"></div>
<input type="hidden" name=cat value=644><button class="btn btn--wd wave waves-effect waves-effect waves-effect sbut" type="submit">Search</button></form></div></div>

<style>.items.am-filter-items-attr_category_ids.am-labels-folding li:nth-child(2){display: none!important;}.searchbit{text-align: center;}.outerinput{max-width: 400px;
    display: inline-block;}.sbut{height: 30px!important;
    margin-bottom: 4px!important;}</style>';
    }



$om = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $om->get('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) {
 $thecustID = $customerSession->getCustomer()->getId();
    $customerSession->getCustomer()->getName(); 
    $customerSession->getCustomer()->getEmail();
    $customerSession->getCustomer()->getGroupId(); // get Customer Group Id


$curl = curl_init();
$loapikey = '5e6790ad6a44445c9158beffa391f78e12';
curl_setopt_array($curl, [
  CURLOPT_URL => "https://pointsforpurposeuat.loyaltynow.com/api/public/members/$thecustID/cards",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_HTTPHEADER => [
    "Accept: text/plain",
    "x-api-key: $loapikey"
  ],
]);

$response = curl_exec($curl);
//print_r($response);
$cardslist = json_decode($response);
}


//$whereweare = "";
if($isLoggedIn) {
    $btnTitle = 'Shop Now';
}
 else {
    $btnTitle = 'Sign in to shop';
}
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    
    <?= $block->getToolbarHtml() ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item">
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
                    <?php // Product Image ?>
                    <?= $productImage->toHtml() ?>
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                        </strong>

			<div class="product-item-name">
                        	<?php /* @escapeNotVerified */ 


                          if ( strpos($block->getProductPrice($_product),'$0.00') === false){
                          echo $block->getProductPrice($_product);
                          }

                          //echo $block->getProductPrice($_product);
                          ?>
                        </div>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                        <?php if($isLoggedIn) {  ?>
                                        <?php
             $productnamer = $_productNameStripped;
             if($selcharpage) {  ?>



             <a href="https://m2.points4purpose.com.au/customer/account/?selected_charity=<?= $productnamer ?>" class="action primary"><span>Select Charity

            <?php } else { 

$afferURL =  $_product->getData('affiliate_url');
//UniqueID=P0000000001317
if (!empty($afferURL))
{


if (str_contains("?", $afferURL)) {

$whole_url  = explode("?",$afferURL);
$whole_url1 = $whole_url[0];
$whole_url2 = $whole_url[1];

}else{

$whole_url1 = $afferURL;

}

}else{
$afferURL = "https://blah";
}


//var_dump($whole_url ); P0000000001317
//https://agoda.uzvs.net/c/1388660/573206/8884?subID1=P0000000001317
$thecustID = str_pad($thecustID, 13, '0', STR_PAD_LEFT);
//2022 changed to go to admin


$whole_url_link = @$whole_url1."?UniqueID=P$thecustID&".@$whole_url2;

//$whole_url_link = '/dadmin/catalog/product/edit/id/'.$_product->getId();


//echo "string".$_product->getData('affiliate_url');
                ?>

<?php if (!empty($cardslist)) { ?>
    <a href="<?= $whole_url_link ?>" target="__blank" class="action primary"><span><?= $btnTitle ?>
<?php } else { ?>
    <a href="javascript:void(null)"  class="action primary nocarlink"><span><?= $btnTitle ?>
<?php } ?>
             


                                             <?php } ?>
                                            </span></a>
                                        <?php } else { ?>
                                          <div class="earning-product-list"><a href="https://points4purpose.com.au/rewardpoints/index/index/" class="rewardpoints-name-img" title="Points Policy"> <img src="https://points4purpose.com.au/skin/frontend/base/default/images/rewardpoints/point.png" alt="Charity Points" style="display: inline-block;"></a>Shop, Save, Earn <br>&amp; Support a Cause</div>
                                          <div class="framelogin" style="color: red;float: left;width:100%;">
<span style="text-decoration: underline;">Sign in</span> <span>to shop</span></div>
                                          </a>
                                        <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?= strpos($pos, $viewMode . '-actions') ?
                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                    $position,
                    'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                ) : '' ?>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
                }
            }
        }

        </script>
    <?php endif; ?>
<?php endif; ?>

<script>

  require(['jquery'],function($){
       $(document).ready(function(){
  $(".nocarlink").on("click",function(){
    //alert('gggg');
    $(".newoverlay").css("display","block")

});
   });

});
var pageBit = document.querySelector(".pages");
var breadcrumbsBit = document.querySelector(".breadcrumbs");
breadcrumbsBit.appendChild(pageBit.cloneNode(true));
</script>


<style>
  .newoverlay {
    position: fixed;
    top: 0px;
    left: 0;
    background: rgba(0,0,0,0.8);
    width: 100%;
    height: 100%;
    z-index: 99;
}

   .newoverlaytext {
    background: #8b8b8b;
    padding: 20px;
    color: #fff;
    font-size: 12px;
    text-align: center;
    position: absolute;
    top: 150px;
    
    left: 0;
    right: 0;
    margin: 0 auto;
    z-index: 999;
    width:325px;
    border-radius:5px;
}

   .newclosebtn{
    position:absolute;
    top: 10px;
    right:10px;
    color:#fff;
   }
</style>

<div class="newoverlay" style="display: none;">
  <div class="newoverlaytext">
      <p>Please link at least one payment card.</p>
      <a class="newclosebtn" style="color:#fff" href="<?php echo $this->getUrl();?>customization/points4purpose/payment">X</a>
  </div>
</div>


