<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<link rel="stylesheet" type="text/css" href="/assets/catpages.css?gfdgfdg"></link>
<style type="text/css">
/* css manish */
.product-items .product-item .product-item-details .product.name.product-item-name {
   height: 45px;
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
}
.products-grid .item.product.product-item .product-item-inner {
    margin: 20px 0;
}

.products-grid .product.details.product-item-details {
    position: relative;
    bottom: 0;
	
}
 .products-grid .product-item .product-image-container{
	      margin-bottom: auto !important;
  }
.product-items .product-item .product-image-wrapper {
	
    padding: 25% !important;
}
@media (max-width: 767px)
  {
	  .products-grid .product.details.product-item-details{
		  bottom: 25px !important;
		  
	  }
	  .product-items .product-item .product-item-info .product-image-container .product-image-wrapper {
    margin-top: 15px;
    padding: 30% !important;
    padding-bottom: 20px !important;
    margin-bottom: 50px;
}
.products-grid .product-item .product-image-container {
    margin: 0px !important;
}
	  
  }
/*End css manish */

  @media (max-width: 500px)
  {
    /* .action.primary, .action-primary, .amshopby-button, .am-filter-go {

    font-size: 8px!important;
} */
  }

  /* JOJ */

  .page-header, .item.product.product-item{box-shadow: 0 3px 10px rgb(0 0 0 / 0.2); !important; border-radius: 5px; margin-bottom: 10px!important;}
  .products-grid .product-item-info{transition:all 0.5s ease;}
  .products-grid .product-item-info:hover, .products-grid .product-item-info.active{
    border:none !important; box-shadow: 0 3px 10px rgb(0 0 0 / 0.2); border-radius: 5px;
  }
  .earning-product-list {
    font-size: 0.9em;
    clear: both;
    margin-bottom: 0.9em;
}
.framelogin,.framelogin a, .framelogin span{    color: red!important;

    
    width: 100%;
}
.breadcrumbs .pages{
  float: right;
      font-size: 10px!important;
}
.breadcrumbs .pages .items .item:after{
  content: unset!important;
  font-family: unset!important;
}

.breadcrumbs .pages .action.next:before,.breadcrumbs .pages .action .next, .breadcrumbs .pages .items .item {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 10px;
    line-height: 12px!important;
  }

.breadcrumbs .page{
  line-height: 18px!important;
}
.breadcrumbs .items{
  max-width: 400px;
    display: inline-block;
}
.breadcrumbs .item:not(:last-child):after {
    
    line-height: unset!important;
    
}
.breadcrumbs .items .item:after{
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 10px;
    line-height: 18px;
   # content: unset!important;
  #  font-family: unset!important;
    margin: unset!important;
    vertical-align: unset!important;
    display: unset!important;
    font-weight: unset!important;
    overflow: unset!important;
    speak:unset!important;
    text-align: center;
}

  .products-grid .product-image-container{
      padding-top: 10px;
	  padding-bottom: 8px;
  }

.product-image-container img {
    max-width: 100%!important;

}
.item.product.product-item {
    padding: unset!important;
}
.cant-find{
  text-align:center!important;

    padding-top: 8px;
}
</style>

<?php

$_productCollection = $block->getLoadedProductCollection();

/*echo "<pre>";
print_r($_productCollection->getData());
die;*/
$count_productCollection = $block->getLoadedProductCollection()->count();
//$productCount = $collection->count();
/** @var \Magento\Catalog\Helper\Output $_helper */
//print_r($block->getLoadedProductCollection());
$_helper = $block->getData('outputHelper');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$context = $objectManager->get('Magento\Framework\App\Http\Context');
$isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
//$whereweare = $block->getRequest()->getParam('id');
$whereweare = $block->getUrl();
 //$query = ['str1' => 'value1', 'str2' => 'value2',];
    $whereweare = $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);


    if (strpos($whereweare, "select-charity") || strpos($whereweare, "682") || strpos($whereweare, "cause")){
        $whereweare = 'yes';
         $selcharpage = 1;
         $csLabel = "Sign in to Support";
         //<style>dli.[data-label]:first-of-type {display:none;} <style>
       /*  echo '<h2 class="title-page ">Select the cause of your choice</h2>
         <div class="container searchbit"><div class="searchinner"><form id="pg-categorysearch-form" class="category-search-form" action="/catalogsearch/result/" method="get" _lpchecked="1"><div class="outerinput">
<input type="text" class="input--full" autocomplete="off" value="" name="q" placeholder="Search for causes" maxlength="128"></div>
<input type="hidden" name=cat value=682><button class="btn btn--wd wave waves-effect waves-effect waves-effect sbut" type="submit">Search</button></form></div></div>
<div class="cant-find"><p>Can\'t find you Charity? <a id="categorySearchBtn" href="/charitysuggestion">Click here</a></p></div>
<style>.title-page{  text-align: center;
    color: #0096a5!important;}.page-title-wrapper{display:none;}.items.am-filter-items-attr_category_ids.am-labels-folding li:nth-child(2){display: none!important;}.searchbit{text-align: center;}.outerinput{max-width: 400px;
    display: inline-block;}.sbut{height: 30px!important;
    margin-bottom: 4px!important;}</style>';*/
    }else{
         $whereweare = 'no';
         $selcharpage = 0;


////////////////////////////////////////
//// COUNt IT USING JS on Frontend ////
//////////////////////////////////////

        // echo 'noncharstuff';
         //echo $count_productCollection.'Items';
        /* echo '<div class="container searchbit"><div class="searchinner"><form id="pg-categorysearch-form" class="category-search-form" action="/catalogsearch/result/" method="get" _lpchecked="1">
<div class="outerinput"><input type="text" class="input--full" autocomplete="off" value="" name="q" placeholder="Search for a store" maxlength="128"></div>
<input type="hidden" name=cat value=644><button class="btn btn--wd wave waves-effect waves-effect waves-effect sbut" type="submit">Search</button></form></div></div>

<style>.items.am-filter-items-attr_category_ids.am-labels-folding li:nth-child(2){display: none!important;}.searchbit{text-align: center;}.outerinput{max-width: 400px;
    display: inline-block;}.sbut{height: 30px!important;
    margin-bottom: 4px!important;}</style>';*/
    }



$om = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $om->get('Magento\Customer\Model\Session');
  $token = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('lofcouponcode/general_settings/token');
//$token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImp0aSI6IlA0UCIsInVuaXF1ZV9uYW1lIjoiYTllMDFhODEtYTI3My00ZTc1LTg1ODMtZWRmNjVhYjY3NWY4IiwiUG9raXRQYWwuQWNjZXNzVHlwZXMiOiJQb2tpdFBhbC5BcGkiLCJQb2tpdFBhbC5BY2Nlc3NSb2xlIjoiTmV0d29yayIsIk5ldHdvcmtJZCI6ImE5ZTAxYTgxLWEyNzMtNGU3NS04NTgzLWVkZjY1YWI2NzVmOCIsImV4cCI6MTY2OTk2OTgxNSwiaXNzIjoiUG9raXRQYWwiLCJhdWQiOiJQNFAifQ.mfSGLOP9Jiizomhnq8VGxyG8WPXIlcAgVIvvSYMXFTY";
$chUrl = '';
$url = 'https://api.pokitpal.com/v1/Association';
if(isset($_REQUEST['q'])){
    $d = explode(" ",$_REQUEST['q']);
    if(count($d) > 1){
        $qparam = end($d);
        $fg = '';
    }else{
        $qparam = $d[0];
    }
    $url = $url."?query=".$qparam;
}

 $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_URL => $url,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => '',
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 0,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => 'GET',
        CURLOPT_HTTPHEADER => array(
            "Content-Type: application/json",
            "Authorization: Bearer $token"
        ),
    ));

    $resAssoc = curl_exec($curl);
    $resAssoc = json_decode($resAssoc, true);
		
    $getAssoc = $resAssoc['associations'];
if($customerSession->isLoggedIn()) {
 $thecustID = $customerSession->getCustomer()->getId();
    $customerSession->getCustomer()->getName(); 
    $customerSession->getCustomer()->getEmail();
	//echo "<pre>";
	$cTokenData = $customerSession->getCustomer()->getData();
	
	//echo "</pre>";
  $cToken = $customerSession->getCustomer()->getCardToken();
    //$cToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJkZXZtYW5pc2hzYWluaUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZGV2bWFuaXNoc2FpbmlAZ21haWwuY29tIiwiU2Vzc2lvbktleSI6ImE1YzZiOTNjLTRhMDctNDYxMC1hMTc3LThmYTk1ZGY5NTkyZSIsIlVzZXJJZCI6IjMwNzY4MzYiLCJOZXR3b3JrSWQiOiJhOWUwMWE4MS1hMjczLTRlNzUtODU4My1lZGY2NWFiNjc1ZjgiLCJQb2tpdFBhbC5BY2Nlc3NUeXBlcyI6IlBva2l0UGFsLkFwaSIsIlBva2l0UGFsLkFjY2Vzc1JvbGUiOiJVc2VyIiwiZXhwIjoxNjcwMzkwMDY1LCJpc3MiOiJQb2tpdFBhbCIsImF1ZCI6ImRldm1hbmlzaHNhaW5pQGdtYWlsLmNvbSJ9.lfb8fJZ8b4IOuZ4WwH6ZLdWJFskkdukXYLu_a44DblM';
   $customerSession->getCustomer()->getGroupId(); // get Customer Group Id
	 $token = $cToken; //loggedin user token to get offers api
    $curl = curl_init();
    curl_setopt_array($curl, [
        CURLOPT_URL => "https://api.pokitpal.com/v1/DebitCards",
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => "",
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 30,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => "GET",
        CURLOPT_HTTPHEADER => [
            "Content-Type: application/json",
            "Authorization: Bearer $cToken"
        ],
    ]);

    $response = curl_exec($curl);
	
$cardslist = json_decode($response);

/*if(!isset($_REQUEST['query'])) {
        $curl = curl_init();
        curl_setopt_array($curl, array(
            CURLOPT_URL => 'https://api.pokitpal.com/v1/OfferGroup',
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => '',
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => 'GET',
            CURLOPT_HTTPHEADER => array(
                "Content-Type: application/json",
                "Authorization: Bearer $cToken"
            ),
        ));

        $resOffers = curl_exec($curl);
        $resOffers = json_decode($resOffers, true);

        $rsInStoreOffer = $resOffers['instore'];
        $rsOnline = $resOffers['online'];
    }*/



    $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_URL => $url,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => '',
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 0,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => 'GET',
        CURLOPT_HTTPHEADER => array(
            "Content-Type: application/json",
            "Authorization: Bearer $cToken"
        ),
    ));

    $resAssoc = curl_exec($curl);
    $resAssoc = json_decode($resAssoc, true);
		
    $getAssoc = $resAssoc['associations'];
	
	//echo "<pre>";
	//print_r($getAssoc);
	//echo "</pre>";
	
}


//die;
$strUrl = 'https://api.pokitpal.com/v1/InstoreOffers/?latitude=-33.872761&longitude=151.205338&distance=1000';
if(isset($_REQUEST['q'])){
    $d = explode(" ",$_REQUEST['q']);
    if(count($d) > 1){
        $qparam = end($d);

    }else{
        $qparam = $d[0];
    }
    $strUrl = $strUrl.'&query='.$qparam;
}

if(isset($_REQUEST['categoryId'])){
    $strUrl = $strUrl . "&categoryId=" . $_REQUEST['categoryId'];
}

$curl = curl_init();
curl_setopt_array($curl, array(
    CURLOPT_URL => $strUrl,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'GET',
    CURLOPT_HTTPHEADER => array(
        "Content-Type: application/json",
        "Authorization: Bearer $token"
    ),
));

$rsInlineOffer = curl_exec($curl);
$rsInlineOffer = json_decode($rsInlineOffer, true);

if(!empty($rsInlineOffer['records'])){
$rsInlineOffer = $rsInlineOffer['records'];
}else{
	$rsInlineOffer = '';
}


//die;
//$whereweare = "";
if($isLoggedIn) {
    $btnTitle = 'Shop Now';
}
 else {
    $btnTitle = 'Sign in to Shop';
}
?>

<?php 
$pagename =  $this->getRequest()->getFullActionName(); 
if($pagename != 'catalogsearch_result_index'){
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
    $cateid = $category->getId();
}
else
{
	 $urldata =	$this->getRequest()->getParam('pcat');
	$cateid = $urldata;
}

$ct = $this->getRequest()->getParam('pcat');

//$cateid = $urldata;

//echo $_productCollection->count();die;	
$chmd = 1;
?>


<?php if ($chmd == 1):?>
<?php 
		$om = \Magento\Framework\App\ObjectManager::getInstance();
		$urlInterface =   $om->get(\Magento\Framework\UrlInterface::class);
        $currentUrl = $urlInterface->getCurrentUrl(); 
if (strpos($currentUrl, "cause.html") !== false){ ?>

<style>
.category-cause .sortfilter {
    display: none;
}
 @media (min-width: 768px)
  {
.category-cause .columns .column.main {
    width: 100% !important;
}
.category-cause .product-items li.item.product.product-item {
    width: calc((100% - 10%)/5) !important;
    margin-left: 20px !important;
}
  }
.category-cause .sidebar-main{
	display: none !important; 
}
</style>



		    <div class="mm products wrapper grid products-grid">
        
		
		
		<?php if(!empty($getAssoc)):?>
		<ol class="products list items product-items">
			  <?php 			 
			  $i=1;
			  foreach ($getAssoc as $clubcharity): ?>
		<li class="item product product-item <?php echo $i;?>">
                <div class="product-item-info" id="product-item-info_2812" data-container="product-grid">
                                                            <span class="product-image-container product-image-container-2812" style="width: 240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="<?php echo $clubcharity['logo'];  ?>" loading="lazy" width="240" height="300" alt="<?php echo $clubcharity['name'];  ?>"></span>
</span>
                  <div class="product details product-item-details">
                                                <strong class="product name product-item-name">
                           <?php echo $clubcharity['name'];  ?>             </strong>

			<div class="product-item-name">
                        	                        </div>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">

                                <?php if($isLoggedIn){ ?>
                                   
                                    <input type="hidden" name="cause_id" id="cause_id" value="<?php echo $clubcharity['id'];  ?>">

                                                 <a href="#" class="action primary charity" data-cause="<?php echo $clubcharity['id'];  ?>" data-id="<?php echo $clubcharity['name'];  ?>"><span>Select Cause 

                </span></a>
                                            <?php }else{ ?>     

                                                <div class="framelogin" style="color: red;float: left;width:100%;">
            <a href="/customer/account/login/referer/" class="btn btn--wd">
       									
            Sign in to Support</a></div>                  



<?php } ?>
           
        </div>
    </div>
    </div>
    </div>
    </div>
        </li>
		
		<?php
			$i++;
		endforeach; ?>
		</ol>
		<?php endif;	?>
		
		</div>
		<?php }	?>


    <?php if (strpos($currentUrl, "rewards-shop.html") !== false) : ?>
	<Style>
	.category-rewards-shop .sortfilter {
    display: none;
}

.product-items .product-item .product-item-details .text-center {
    min-height: 36px;
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
}
</Style>
<h3> Please select offers from the categories below </h3>
<?php
$ct = $this->getRequest()->getParam('pcat');
$url = 'https://api.pokitpal.com/v1/OnlineOffers';

$pageSize='48';

if(isset($_REQUEST['q'])){
    $d = explode(" ",$_REQUEST['q']);
    if(count($d) > 1){
        $qparam = end($d);
        $fg = '';
    }else{
        $qparam = $d[0];
    }
    $url = $url."?query=".$qparam."&pageSize=".$pageSize;
}else{
	

    if(isset($ct)) {
        $url = $url . "?categoryId=" . $ct."&pageSize=".$pageSize;
    }else{
        $url = $url."?pageSize=".$pageSize;
    }

}
if(isset($_REQUEST['page'])){
	$url = $url."&pageNumber=".$_REQUEST['page']."&pageSize=".$pageSize;
}
$curl = curl_init();
curl_setopt_array($curl, array(
    CURLOPT_URL => $url,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'GET',
    CURLOPT_HTTPHEADER => array(
        "Content-Type: application/json",
        "Authorization: Bearer $token"
    ),
));


$responseOffersOnline = curl_exec($curl);
$rsOffersOnlinedata = json_decode($responseOffersOnline, true);
if(isset($rsOffersOnlinedata['records'])){
    $rsOffersOnline = $rsOffersOnlinedata['records'];
}else{
	$rsOffersOnline =  '';
	
}
?>	

<div class="products wrapper grid products-grid">

    <?php if(!empty($rsOffersOnline)):?>
        <h2 class="md-title"><?= __('Online Offers')?></h2>
    <ol class="products list items product-items " >
        <?php foreach ($rsOffersOnline as $onlineOffr):?>
            <li class="item product product-item">
                <div class="product-item-info" id="product-item-info_9309" data-container="product-grid">
                                                            <span class="product-image-container product-image-container-9309" style="width: 240px;">
    <span class="product-image-wrapper" style="padding-bottom: 25%;">
        <img class="product-image-photo-o" src="<?= $onlineOffr['logo']?>" loading="lazy" width="240" height="300" alt="Crowne Plaza Queenstown"></span>
</span>                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <?= $onlineOffr['advertiser'];?>                        </strong><p class="text-center">   <?= $onlineOffr['title'];?>    </p>

                        <div class="product-item-name">
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="9309" data-price-box="product-id-9309">
    <span class="special-price">


<span class="price-container price-final_price tax weee">
            <span class="price-label">  <?= $onlineOffr['advertiser'];?> </span>
        <span id="product-price-9309" data-price-amount="109" data-price-type="finalPrice" class="price-wrapper "><span class="price"><?= __('Online')?></span></span>
        </span>
    </span>

                            </div>                        </div>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">


                                    <div class="earning-product-list">Shop, Save, Earn <br>&amp; Support a Cause</div>
                                    <div class="framelogin" style="color: red;float: left;width:100%;">
                                        <?php if($isLoggedIn){ ?>
                                        <a href="<?= $onlineOffr['trackingUrl']?>" target="_blank" class="btn btn--wd">

                                            <?= $btnTitle; ?></a>
                                            <?php }else{ ?>
                                            <a href="<?= $block->escapeUrl($block->getUrl('customer/account/login', ['referer' => base64_encode($this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]))])); ?>" class="btn btn--wd"> <?= $btnTitle; ?></a>

                                        <?php } ?>
                                            </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>

        <?php endforeach; ?>
    </ol>
	
	<?php 
	if($rsOffersOnlinedata['totalPages']>1){ // online offers pagination start
		?>
	<div class="pages">
            
            <ul class="items pages-items" aria-labelledby="paging-label">
<?php

$ct = $this->getRequest()->getParam('pcat');
$pageno = $this->getRequest()->getParam('page');
if(empty($pageno)){
$pageno=1;	
}
for($page = 1; $page<= $rsOffersOnlinedata['totalPages']; $page++) {  
		
if($page==$pageno){  ?>
		 <li class="item current">
                        <strong class="page">
                            
                            <span><?php echo $page; ?></span>
                        </strong>
                    </li>
<?php

}else{
?>
        <li class="item"><a class="page" href="rewards-shop.html?cat=<?php echo $ct ?>&page=<?php echo $page ?>" ><?php echo $page; ?> </a></li> 
   <?php
 } 
} 
?>
</ul>
</div> 
	<?php } // online offers pagination end ?>
    <?php
    else:
        echo 'No Online Offer found';
    endif; ?>
        <?php /* if(!empty($rsInlineOffer)): ?>
            <h2 class="md-title"><?= __('In Store Offers')?></h2>
            <ol class="products list items product-items">
        <?php  foreach ($rsInlineOffer as $iOffr):?>
            <li class="item product product-item">
                <div class="product-item-info" id="product-item-info_9309" data-container="product-grid">
                                                            <span class="product-image-container product-image-container-9309" style="width: 240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo-o" src="<?= $iOffr['logoUrl']?>" loading="lazy" width="240" height="300" alt="Crowne Plaza Queenstown"></span>
</span>                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <?= $iOffr['advertiserName'];?>                        </strong><p class="text-center">   <?= $iOffr['offerTitle'];?>    </p>

                        <div class="product-item-name">
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="9309" data-price-box="product-id-9309">
    <span class="special-price">


<span class="price-container price-final_price tax weee">
            <span class="price-label">  <?= $iOffr['advertiserName'];?> </span>
        <span id="product-price-9309" data-price-amount="109" data-price-type="finalPrice" class="price-wrapper "><span class="price"><?= __('InStore')?></span></span>
        </span>
    </span>

                            </div>                        </div>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">


                                    <div class="earning-product-list">Shop, Save, Earn <br>&amp; Support a Cause</div>
                                    <div class="framelogin" style="color: red;float: left;width:100%;">
                                        <?php if($isLoggedIn){ ?>
                                            <a href="<?= $this->getUrl()."in-offers?id=".$iOffr['offerId']?>" target="_blank" class="btn btn--wd">
                                                <?= 'View Offer'; ?></a>
                                        <?php }else{ ?>
                                            <a href="<?= $block->escapeUrl($block->getUrl('customer/account/login', ['referer' => base64_encode($this->getUrl('', ['_current' => true, '_use_rewrite' => true]))])); ?>" class="btn btn--wd"> <?= $btnTitle; ?></a>

                                        <?php } ?></div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach;  ?>
    </ol>
        <?php
            else:
            echo 'No InStore Offer found';
        endif; */ ?>

</div>
    <?php endif; ?>
<?php else: ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    
    <?= $block->getToolbarHtml() ?>
	
	
	
    <div class="mm products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
		<?php 
		$om = \Magento\Framework\App\ObjectManager::getInstance();
		$urlInterface =   $om->get(\Magento\Framework\UrlInterface::class);
 $currentUrl = $urlInterface->getCurrentUrl();
		if (strpos($currentUrl, "cause.html") !== false){
		
		if(!empty($getAssoc)):?>
			  <?php foreach ($getAssoc as $clubcharity): ?>
		<li class="item product product-item">
                <div class="product-item-info" id="product-item-info_2812" data-container="product-grid">
                                                            <span class="product-image-container product-image-container-2812" style="width: 240px;">
    <span class="product-image-wrapper" style="padding-bottom: 125%;">
        <img class="product-image-photo" src="<?php echo $clubcharity['logo'];  ?>" loading="lazy" width="240" height="300" alt="<?php echo $clubcharity['name'];  ?>"></span>
</span>
                  <div class="product details product-item-details">
                                                <strong class="product name product-item-name">
                           <?php echo $clubcharity['name'];  ?>             </strong>

			<div class="product-item-name">
                        	                        </div>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">

                                <?php if($isLoggedIn){ ?>
                                   
                                    <input type="hidden" name="cause_id" id="cause_id" value="<?php echo $clubcharity['id'];  ?>">

                                                 <a href="#" class="action primary charity" data-cause="<?php echo $clubcharity['id'];  ?>" data-id="<?php echo $clubcharity['name'];  ?>"><span>Select Cause 

                </span></a>
                                            <?php }else{ ?>     

                                                <div class="framelogin" style="color: red;float: left;width:100%;">
            <a href="/customer/account/login/referer/" class="btn btn--wd">
       									
            Sign in to Support</a></div>                  



<?php } ?>
           
        </div>
    </div>
    </div>
    </div>
    </div>
        </li>
		<?php endforeach; ?>
		<?php endif;
		}		?>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item">
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
                    <?php // Product Image ?>
                    <?= $productImage->toHtml() ?>
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                        </strong>

			<div class="product-item-name">
                        	<?php /* @escapeNotVerified */ 


                          if ( strpos($block->getProductPrice($_product),'$0.00') === false){
							  if ( strpos($block->getProductPrice($_product),'$0') === false){
							 
                        	  	echo $block->getProductPrice($_product);
							  }
					      }

                          //echo $block->getProductPrice($_product);
                          ?>
                        </div>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                        <?php 
										$productnamer='';
										if($isLoggedIn) {  ?>
                                        <?php
             $productnamer = $_productNameStripped;
             if($selcharpage) {  ?>

                                    <input type="hidden" name="cause_id" id="cause_id" value="<?= $_product->getPokitpalCharityId();?>">

                                    <?php $chUrl = 'https://points4purpose.com.au/customer/account/?selected_charity='.$productnamer; ?>
             <a href="#" class="action primary charity" data-cause="<?= $_product->getPokitpalCharityId();?>" data-id="<?php echo $productnamer;?>"><span>Select Cause

            <?php } else { 

$afferURL =  $_product->getData('affiliate_url');
//UniqueID=P0000000001317
if (!empty($afferURL))
{


if (str_contains("?", $afferURL)) {

$whole_url  = explode("?",$afferURL);
$whole_url1 = $whole_url[0];
$whole_url2 = $whole_url[1];

}else{

$whole_url1 = $afferURL;

}

}else{
$afferURL = "https://blah";
}


//var_dump($whole_url ); P0000000001317
//https://agoda.uzvs.net/c/1388660/573206/8884?subID1=P0000000001317
$thecustID = str_pad($thecustID, 13, '0', STR_PAD_LEFT);
//2022 changed to go to admin


$whole_url_link = @$whole_url1."?UniqueID=P$thecustID&".@$whole_url2;

//$whole_url_link = '/dadmin/catalog/product/edit/id/'.$_product->getId();


//echo "string".$_product->getData('affiliate_url');
                ?>

<?php if (!empty($cardslist)) { ?>
    <div class="earning-product-list">Shop, Save, Earn <br>&amp; Support a Cause</div>
    <a href="<?= $whole_url_link ?>" target="__blank" class="action primary"><span><?= $btnTitle ?>
<?php } else { ?>
    <div class="earning-product-list">Shop, Save, Earn <br>&amp; Support a Cause</div>
    <a href="javascript:void(null)"  class="action primary nocarlink"><span><?= $btnTitle ?>
<?php } ?>           
    <?php } ?>
    </span></a>
    <?php } else { ?>

        <?php if(strpos($whereweare, "select-charity") || strpos($whereweare, "682") || strpos($whereweare, "cause") || $whereweare == 'yes') { 
            $text = ""; ?>   
               <div class="earning-product-list"><?php echo $text; ?></div>
        <?php } else {
            $text = "Shop, Save, Earn <br>&amp; Support a Cause"; ?> 
        <div class="earning-product-list"><?php echo $text; ?></div>
        <?php }  ?>
        <div class="framelogin" style="color: red;float: left;width:100%;">
            <a href="<?= $block->escapeUrl($block->getUrl('customer/account/login', ['referer' => base64_encode($this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]))])); ?>" class="btn btn--wd">
       									
            <?php if(!empty($csLabel)) { echo __('Sign in to Support');}else{ echo __('Sign in to Shop');}?></a></div>
            </a>
    <?php } ?>
    </div>
    </div>
    </div>
    </div>
    </div>
    <?= strpos($pos, $viewMode . '-actions') ?
        /* @noEscape */ $secureRenderer->renderStyleAsTag(
        $position,
        'product-item-info_' . $_product->getId() . ' div.product-item-actions'
        ) : '' ?>
    </li>

    <?php endforeach; ?>


    </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
                }
            }
        }

        </script>
    <?php endif; ?>
<?php endif; ?>

<script>

  require(['jquery'],function($){
       $(document).ready(function(){
  $(".nocarlink").on("click",function(){
    //alert('gggg');
    $(".newoverlay").css("display","block")

});
   });

});
var pageBit = document.querySelector(".pages");
var breadcrumbsBit = document.querySelector(".breadcrumbs");
breadcrumbsBit.appendChild(pageBit.cloneNode(true));
</script>


<style>
  .newoverlay {
    position: fixed;
    top: 0px;
    left: 0;
    background: rgba(0,0,0,0.8);
    width: 100%;
    height: 100%;
    z-index: 99;
}

   .newoverlaytext {
    background: #8b8b8b;
    padding: 20px;
    color: #fff;
    font-size: 12px;
    text-align: center;
    position: absolute;
    top: 150px;
    
    left: 0;
    right: 0;
    margin: 0 auto;
    z-index: 999;
    width:325px;
    border-radius:5px;
}

   .newclosebtn{
    position:absolute;
    top: 10px;
    right:10px;
    color:#fff;
   }
   
   .sidebar.sidebar-main.hidesidebar
   {
	   display:none;
   }
   .column.main.fullwidth{
	   width: 100%;
    float: none;
}
</style>

<div class="newoverlay" style="display: none;">
  <div class="newoverlaytext">
      <p>Please link at least one payment card.</p>
      <a class="newclosebtn" style="color:#fff" href="<?php echo $this->getUrl();?>customization/points4purpose/payment">X</a>
  </div>
</div>

<div id="popup-modal" style="display:none;" class="charitysuccess">
    <div class="text-center">
        <div class="divider divider--xs"></div>
        <p class="msg-success">Successfully added to your profile.</p>
        <div class="divider divider--xs"></div>

        <a href="<?= $this->getUrl();?>customization/charity/" class="btn btn--wd  wishlist-hide go-to-profile-link">Go to Profile</a>
        <div class="divider divider--xs wishlist-hide"></div>
    </div>
</div>



<script type="text/javascript">


        require(
        [
        'jquery',
        'Magento_Ui/js/modal/modal'
        ],
        function(
        $,
        modal
        ) {
        var options = {
        type: 'popup',
        responsive: true,
        innerScroll: true
    };

        var popup = modal(options, $('#popup-modal'));
        $(".charity").on('click',function(){
			
			<?php $chUrl = $this->getUrl().'customization/charity/charityupdate'; ?>
			
			var charity = $(this).attr('data-id');
            var causeId = $(this).attr('data-cause');
			
			
            $.ajax({
                type: "POST",
                url: "<?php echo $chUrl;?>",
                data: 'selected_charity='+charity+'&cause_id='+causeId,
                cache: false,
                success: function(result){
                   // alert(result);
				   
				   $("#popup-modal").modal("openModal");
                }
            });

          //  $.get('<?php echo $chUrl ?>',function(){
            });

       // $("#popup-modal").modal("openModal");
    });

  


require([
        'jquery'
],
function ($) {
	
	<?php if($cateid == '682') {?>
		
		jQuery('.sortfilter .sorter-options option').text('Cause');
		jQuery('.column.main #amasty-shopby-product-list .toolbar-products .sorter-options option').text('Cause');
		
		<?php }else{ ?> 
		jQuery('.sortfilter .sorter-options option').text('Store');
		jQuery('.column.main #amasty-shopby-product-list .toolbar-products .sorter-options option').text('Store');
		<?php }	?>	
			
      //  $(".categorybuttonass").click(function(){
			 $('body').on('click',".categorybuttonass",function(){
			
		//$('body').on('click','')	
		
		if($('.sidebar.sidebar-main').hasClass('hidesidebar'))
		{
			//alert('dsfsddsf');
			$('.sidebar.sidebar-main').removeClass('hidesidebar');
			$('.column.main').removeClass('fullwidth');
		}
		else
		{
			$('.sidebar.sidebar-main').addClass('hidesidebar');
			$('.column.main').addClass('fullwidth');
		}
			
		//	alert('jakkers');
		});
		
		
		
				
			//	alert('ddd');
				
				
				
			
			
    });
	

window.addEventListener("load", function(){
setTimeout(function(){
	
	//jQuery('.column.main #amasty-shopby-product-list .toolbar-products .modes').html(' ');
	
	setInterval(function () {
			if(jQuery('.column.main #amasty-shopby-product-list .toolbar-products .modes-mode').hasClass('active'))
				{
					var dataval = jQuery('.column.main #amasty-shopby-product-list .toolbar-products .modes-mode.active').attr('data-value');
					console.log(dataval);
					//if(dataval == 'list'){
						console.log('change');
						var modeshtml = jQuery('.column.main #amasty-shopby-product-list .toolbar-products').html();
						jQuery('.sortfilter #amasty-shopby-product-list .toolbar-products').html(modeshtml);
						
						
					/*	var modeshtml = jQuery('.column.main #amasty-shopby-product-list .toolbar-products .modes').html();
						jQuery('.sortfilter #amasty-shopby-product-list .toolbar-products .modes').html(modeshtml);*/
						
					//	clearInterval();
					//}
		}
		
		}, 5000);
		
		
	//	jQuery('.sortfilter #amasty-shopby-product-list .toolbar-products .modes a').click(function(){
			
			jQuery('body').on('click', '.sortfilter #amasty-shopby-product-list .toolbar-products .modes a', function(){
			var attrid =jQuery(this).attr('id');
				 jQuery('.column.main #amasty-shopby-product-list .toolbar-products .modes a#'+attrid).click();
			});
			
			
			
			jQuery('body').on('click', '.sortfilter #amasty-shopby-product-list .toolbar-products .pages a', function(){
			var attrid =jQuery(this).attr('href');
			//alert(attrid);
		
				jQuery('.column.main #amasty-shopby-product-list .toolbar-products .modes a').each(function(){
					
					if(jQuery(this).attr('href') == attrid){
							jQuery(this).trigger();
						}
					});
		
			//	 jQuery('.column.main #amasty-shopby-product-list .toolbar-products .modes a#'+attrid).click();
			});
			
			
			
		
			
		
 }, 1500);
		  
		 	
	});


	
</script>


