<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<style>
	.page-footer {
    padding-bottom: 0px !important;
}
.footer.content ul {
    padding-right: 0;
}


   li.item.product.product-item{
        padding: 0px;
    }
 .product-image-container img {
        max-width: 100%;
        margin-left: 0;
        margin-right: 0;
    }
</style>
 
 
<div class="footer content">
    <?php echo $this->getLayout() ->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_links_block')->toHtml();
?>
	
</div>
<small class="copyright">
    <span><?= $block->escapeHtml($block->getCopyright()) ?></span>
</small>