<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Resetpassword $block */
?>
<form action="<?= $block->escapeUrl($block->getUrl('*/*/resetpasswordpost', ['_query' => ['token' => $block->getResetPasswordLinkToken()]])) ?>"
      method="post"
        <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?>
      id="form-validate"
      class="form password reset"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                       data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirmation required">
            <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'#password'}" autocomplete="off">
            </div>
        </div>
        <div class="field recaptcha">
            <div class="g-recaptcha" name="recaptcha" id="g-recaptcha-response" data-sitekey="6LdTCJIeAAAAAK_Q3JaBRraeslK_EM9uFU1g-0eV"></div>
            <span class="g-recaptcha-error" style="color: red;display: none">You need to select reCAPTCHA</span>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Set a New Password')) ?></span></button>
        </div>
    </div>
</form>


<script type="text/javascript">
    require([
        'jquery',
        'jquery/ui',
        'jquery/validate',
        'mage/translate'
    ], function($){

        $('#form-validate .primary').click(function(){
            var exists = $("#g-recaptcha-response").val();
            if(exists === ''){
                $(".g-recaptcha-error").css('display','block');
                return false;
            }
        });

    });


</script>


<script type="text/javascript">

    function capatcheFunction() {
        var exists = document.getElementById("g-recaptcha-response");
        if(exists == null){

        } else{
            var check = document.getElementById("g-recaptcha-response").value;
            if(check=='' || check == null){
                document.getElementById("recaptcha").style.border = "1px solid #ea0e0e";
                return false;
            }
            else{
                document.getElementById("recaptcha").style.border = "none";
                return true;
            }
        }
    }
</script>